export const VALIDATE_FORM = 'VALIDATE_FORM';
export const VALIDATE_FORM_SUCCESS = 'VALIDATE_FORM_SUCCESS';
export const VALIDATE_FORM_ERROR = 'VALIDATE_FORM_ERROR';

export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR';

export const START_PRODUCTS_DOWNLOAD = 'START_PRODUCTS_DOWNLOAD';
export const PRODUCTS_DOWNLOAD_SUCCESS = 'PRODUCTS_DOWNLOAD_SUCCESS';
export const PRODUCTS_DOWNLOAD_ERROR = 'PRODUCTS_DOWNLOAD_ERROR';

export const PRODUCT_TO_DELETE = 'PRODUCT_TO_DELETE';
export const PRODUCT_DELETED_SUCCESS = 'PRODUCT_DELETED_SUCCESS';
export const PRODUCT_DELETED_ERROR = 'PRODUCT_DELETED_ERROR';

export const PRODUCT_TO_EDIT = 'PRODUCT_TO_EDIT';
export const PRODUCT_EDITED_SUCCESS = 'PRODUCT_EDITED_SUCCESS';
export const PRODUCT_EDITED_ERROR = 'PRODUCT_EDITED_ERROR';

export const START_EDITING_PRODUCT = 'START_EDITING_PRODUCT';
export const EDITED_PRODUCT_SUCCESS = 'EDITED_PRODUCT_SUCCESS';
export const EDITED_PRODUCT_ERROR = 'EDITED_PRODUCT_ERROR';